### ISSUE TITLE
Hide complications and second hand

### ISSUE THREAD

**Issue by planewave** [ElChoquito/AutomaticWatchFaces#3]
Hi there

Your work is great. I especially like the digit watch faces without complications (even without the second hand). Something like the Hermes one, elegant and easy to read.
So could you add the option such that the complications in other watch faces can be hidden? especially the Patek Philippe grand complication? Also the option to hide the GMT hand in Rolex Explorer and GMT master? The GMT function didn't work(?) and is not useful most of the time.

Also, could you add another colour theme like this, or hide the second hand. Orange colour digits perhaps?  That will be beautiful.
![kdsgbnh](https://user-images.githubusercontent.com/10617156/53859932-347fa100-3f94-11e9-8274-d835e2ddd187.png)

Thank you

**Comment by ElChoquito** [comment]
Hey ! 
The 1.0 update will add new features like hands selection. The GMT function works , just Force Touch your screen and click on "GMT" logo, then scroll the Digital Crown like a real watch. Force touch again your screen and click on "GMT" in order to save the setting. All the informations are available on the readme file.

Sylvain,
